#!/usr/bin/env python3
# ========================================================================
# 역할: 실행 폴더(.runtime/M1 또는 M2) 만들기. runtime_manifest.json 에 적힌 대로 원본 파일을 실행 위치에 링크(또는 복사)하고,
#       runtime.env, start_action.sh, systemd 유닛(base/camera/nav-control/rest-ready/action)을 생성한다.
# 실행: robot.py configure 가 호출. 링크 방식이라 원본(AMR/common, M1, M2)을 고치면 실행 폴더에 바로 반영된다(서비스 재시작 필요).
# ========================================================================
"""Assemble one profile inside AMR; linked sources remain directly editable in Git."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shlex
import shutil
import yaml

ROOT = Path(__file__).resolve().parents[1]


# 매니페스트 검사 → 링크/복사 → 환경 파일·유닛·실행 스크립트 생성.
def materialize(robot, output, linked=False):
    if robot not in ('M1', 'M2'):
        raise ValueError('Choose M1 or M2')
    manifest = json.loads((ROOT/robot/'runtime_manifest.json').read_text())
    out = Path(output).absolute()
    if out.exists():
        raise ValueError('Output already exists; archive it before configuring again: '+str(out))
    if any(c.isspace() or c in '\"\'\\%$`' for c in str(out)):
        raise ValueError('Runtime path must not contain whitespace or shell/systemd metacharacters')
    profile = yaml.safe_load((ROOT/robot/'config/robot.yaml').read_text())
    if profile['robot_id'] != robot or profile['runtime_namespace'] != manifest['runtime_robot']:
        raise ValueError('Profile identity mismatch')
    name = manifest['runtime_robot']
    workspace = out/'final_robot_ws'
    camera = out/manifest['camera_directory']
    targets = {'workspace':workspace, 'camera':camera, 'units':out/'units'}
    plan = []
    for entry in manifest['files']:
        source = (ROOT/entry['source']).resolve()
        if not source.is_relative_to(ROOT) or not source.is_file():
            raise ValueError('Invalid source: '+entry['source'])
        if not linked and hashlib.sha256(source.read_bytes()).hexdigest() != entry['sha256']:
            raise ValueError('Manifest mismatch: '+entry['source'])
        kind, rel = entry['target'].split('/', 1)
        dest = targets[kind]/rel
        if not dest.resolve().is_relative_to(targets[kind]):
            raise ValueError('Invalid destination: '+entry['target'])
        plan.append((source, dest, kind))
    out.mkdir(parents=True)

    # 파일 하나를 링크 또는 복사.
    def install(source, dest, link=linked):
        dest.parent.mkdir(parents=True, exist_ok=True)
        if link:
            dest.symlink_to(os.path.relpath(source, dest.parent))
        else:
            shutil.copy2(source, dest)

    for source, dest, kind in plan:
        if dest == workspace/'handoff/pc_env.bash':
            continue
        # DDS files are regenerated by runtime programs, not source edits.
        install(source, dest, linked and kind != 'units' and not dest.name.startswith('dds_'))
        if kind == 'units':
            text = dest.read_text()
            for old in ('/home/ubuntu/final_robot_ws', '%h/final_robot_ws', '$HOME/final_robot_ws'):
                text = text.replace(old, str(workspace))
            for old in ('/home/ubuntu/'+manifest['camera_directory'], '%h/'+manifest['camera_directory']):
                text = text.replace(old, str(camera))
            dest.write_text(text)
    for source_root in (ROOT/'common/src/amr_mission', ROOT/'interfaces/host_pkg'):
        for source in source_root.rglob('*'):
            if not source.is_file() or '__pycache__' in source.parts or source.suffix == '.pyc':
                continue
            install(source, workspace/'host_ws/src'/source_root.name/source.relative_to(source_root))
    nav = workspace/'robot'/name/'navigation'
    if not (nav/'action_gate.py').exists():
        install(ROOT/'common/navigation/action_gate.py', nav/'action_gate.py')
    (nav/'action_profile.json').write_text(json.dumps(profile, indent=2)+'\n')
    environment = dict(AMR_WORKSPACE=str(workspace), AMR_CAMERA=str(camera), AMR_ROBOT=name,
                       BURGER_PROJECT_ROOT=str(workspace), BURGER_NAV2_BASE_DIR=str(camera),
                       ROS_DOMAIN_ID=str(profile['ros_domain_id']), TURTLEBOT3_MODEL='burger', LDS_MODEL='LDS-02')
    # Python resolves a symlink entry point's import directory to common/.
    # Keep profile-local modules and the flat camera package on the import path.
    (out/'runtime.env').write_text(''.join('export '+key+'='+shlex.quote(value)+'\n' for key,value in environment.items())+
        'export PYTHONPATH="$AMR_WORKSPACE/robot/$AMR_ROBOT/navigation:$AMR_CAMERA${PYTHONPATH:+:$PYTHONPATH}"\n')
    env = workspace/'handoff/pc_env.bash'
    env.parent.mkdir(parents=True, exist_ok=True)
    env.write_text(f'''source "{out}/runtime.env" || return 1
source "{workspace}/handoff/ros_setup_fast.bash" || return 1
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
unset ROS_LOCALHOST_ONLY ROS_AUTOMATIC_DISCOVERY_RANGE ROS_STATIC_PEERS ROS_DISCOVERY_SERVER
unset FASTRTPS_DEFAULT_PROFILES_FILE FASTDDS_DEFAULT_PROFILES_FILE
''')
    units = out/'units'
    units.mkdir(exist_ok=True)
    for suffix, script in [('base',camera/'start_base.sh'), ('camera',camera/'start_camera.sh'),
                           ('nav-control',nav/'nav_control_service.sh')]:
        (units/f'{name}-{suffix}.service').write_text(f'[Unit]\nDescription={robot} {suffix}\n[Service]\nType=simple\nExecStart=/bin/bash {script}\nKillSignal=SIGINT\nTimeoutStopSec=20\nRestart=no\n')
    (units/f'{name}-rest-ready.service').write_text(f'[Unit]\nDescription={robot} REST standby (no idle GPIO or motor publisher)\nPartOf={name}-nav-control.service\n[Service]\nType=simple\nExecStart=/bin/bash {nav}/start_rest_ready.sh\nEnvironment=ROS_DOMAIN_ID=40\nRestart=on-failure\nRestartSec=2\nKillSignal=SIGINT\nTimeoutStopSec=12\nUMask=0077\n')
    action = out/'start_action.sh'
    action.write_text(f'''#!/usr/bin/env bash
set -eo pipefail
source "{out}/runtime.env"
source "{nav}/nav_env.bash"
exec ros2 run amr_mission action_server --ros-args -r __ns:=/{robot} -p robot_id:={robot} -p runtime_robot:={name} -p navigation_dir:={nav} -p action_name:={profile['action_name']} "$@"
''')
    action.chmod(0o755)
    (units/f'{robot.lower()}-action.service').write_text(f'[Unit]\nDescription={robot} robot action server\nAfter={name}-motion-owner.service\n[Service]\nType=simple\nExecStart=/bin/bash {action}\nKillSignal=SIGINT\nTimeoutStopSec=25\nRestart=no\n')
    (out/'runtime.json').write_text(json.dumps(dict(robot_id=robot, runtime_robot=name, workspace=str(workspace),
        camera=str(camera), navigation=str(nav), units=str(units), repository=str(ROOT), linked=linked), indent=2)+'\n')
    return out


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('robot', choices=['M1','M2'])
    parser.add_argument('--output', required=True)
    parser.add_argument('--linked', action='store_true')
    args = parser.parse_args()
    print(materialize(args.robot, args.output, args.linked))
